import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import Header from "../components/Header";
import { useEffect, useRef } from "react";
import { useMoveToDiv } from "../utils/useMoveToDiv";

export default function App({ Component, pageProps }: AppProps) {
  const outterDiv = useRef<HTMLDivElement>(null);

  return (
    <>
      <div ref={outterDiv}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Component {...pageProps} />
      </div>
    </>
  );
}
